[package]
name = "caravel"
version = "0.1.0"
authors = ["Sawyer Herbst <sawyer.herbst@myparadigm.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
