use crate::position::Span;
use crate::source_string::SourceString;

#[derive(Clone, Debug)]
pub struct Token {
  pub pos: Span,
  pub kind: TokenKind,
}

#[derive(Clone, Debug)]
pub enum TokenKind {
  Identifier(SourceString),

  FloatLiteral(SourceString),

  // Operators
  // Arithmetic Operators
  Add,
  Subtract,
  Multiply,
  Divide,
  Modulo,
  // Assignment Operators
  Assignment,

  Eol,

  LParen,
  RParen,
  RBracket,
  LBracket,
  Colon,

  // Keywords
  Let,

  /// Special token, used by the parser to signify
  /// the end of the token stream. Will never be
  /// generated by the lexer
  Eof,
}
