use crate::position::Position;

#[derive(Clone, Debug)]
pub enum TokenType {
  Identifier(String),

  FloatLiteral(String),

  // Operators
  // Arithmetic Operators
  Add,
  Subtract,
  Multiply,
  Divide,
  Modulo,
  // Assignment Operators
  Assignment,

  Eol,

  LParen,
  RParen,
  RBracket,
  LBracket,
  Colon,

  // Keywords
  Let,

  /// Special token, used by the parser to signify
  /// the end of the token stream. Will never be
  /// generated by the lexer
  Eof,
}

#[derive(Clone, Debug)]
pub struct Token {
  pub token_type: TokenType,
  pub start_pos: Position,
  pub source_len: u32,
}
